name: dub
version: 1.32.1
summary: Package and build manager for D applications and libraries
description: |
    DUB is a build tool for projects written in the D programming
    language, with support for automatically retrieving dependencies
    and integrating them into the build process.

base: core18
confinement: classic
grade: stable
license: MIT AND BSL-1.0

apps:
  dub:
    command: bin/dub
    environment:
      LD_LIBRARY_PATH: $SNAP/release:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu

parts:
  dub:
    source: https://github.com/dlang/dub.git
    source-tag: v1.32.1
    source-type: git
    plugin: dump
    override-build: |
        ../../../stage/bin/dmd -run ./build.d
        snapcraftctl build
    stage:
    - bin/dub
    build-packages:
    - build-essential
    - libcurl4-gnutls-dev
    after:
    - dmd
    - dmd-config
    - phobos

  dub-license:
    plugin: dump
    source: doc
    organize:
      LICENSE: doc/LICENSE

  curl:
    plugin: nil
    stage-packages:
    - libcurl3-gnutls

  dmd:
    source: https://github.com/dlang/dmd.git
    source-tag: &dmd-version v2.103.1
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - AUTO_BOOTSTRAP=1
    - ENABLE_RELEASE=1
    override-build: |
      snapcraftctl build
      make -C druntime -f posix.mak install
    organize:
      linux/bin32: bin
      linux/bin64: bin
      src/druntime/import: import/druntime
    stage:
    - -bin/dmd.conf
    - -linux
    - -samples
    prime:
    - -*
    build-packages:
    - curl
    - g++

  dmd-config:
    plugin: dump
    source: dmd-config
    organize:
      dmd.conf: bin/dmd.conf
    prime:
    - -*

  phobos:
    source: https://github.com/dlang/phobos.git
    source-tag: *dmd-version
    source-type: git
    plugin: make
    makefile: posix.mak
    make-parameters:
    - CUSTOM_DRUNTIME=1
    - DMD_DIR=../../dmd/build
    - DRUNTIME_PATH=../../dmd/build/druntime
    - VERSION=../../dmd/build/VERSION
    organize:
      linux/lib32: lib32
      linux/lib64: lib64
      src/phobos: import/phobos
    stage:
    - -linux
    - -src
    prime:
    - -*
    build-packages:
    - gcc
    after:
    - dmd
